---
title: "Indian IT Stock Prices over the years"
author: "Muhammad Mudassir Khan"
date: "November 10, 2016"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Top Indian IT Stock Prices

```{r, message=FALSE, warning=FALSE}
library(dplyr)
library(plotly)
library(lubridate)
infy <- readRDS("infy_stock.Rda")
tcs <- readRDS("tcs_stock.Rda")
wipro <- readRDS("wipro_stock.Rda")
hcl <- readRDS("hcl_stock.Rda")

y_infy <- infy %>% filter(day(Date) == 31 & month(Date) == 12) %>% mutate(Stock = "Infosys")
y_tcs <- tcs %>% filter(day(Date) == 31 & month(Date) == 12) %>% mutate(Stock = "TCS")
y_wipro <- wipro %>% filter(day(Date) == 31 & month(Date) == 12) %>% mutate(Stock = "Wipro")
y_hcl <- hcl %>% filter(day(Date) == 31 & month(Date) == 12) %>% mutate(Stock = "HCL")
y_infy[10, ] <- infy %>% filter(Date == "2006-12-29") %>% mutate(Stock = "Infosys")
y_infy[11, ] <- infy %>% filter(Date == "2005-12-30") %>% mutate(Stock = "Infosys")
y_tcs[10, ] <- tcs %>% filter(Date == "2006-12-29") %>% mutate(Stock = "TCS")
y_tcs[11, ] <- tcs %>% filter(Date == "2005-12-30") %>% mutate(Stock = "TCS")
y_wipro[10, ] <- wipro %>% filter(Date == "2006-12-29") %>% mutate(Stock = "Wipro")
y_wipro[11, ] <- wipro %>% filter(Date == "2005-12-30") %>% mutate(Stock = "Wipro")
y_hcl[10, ] <- hcl %>% filter(Date == "2006-12-29") %>% mutate(Stock = "HCL")
y_hcl[11, ] <- hcl %>% filter(Date == "2005-12-30") %>% mutate(Stock = "HCL")

combined <- rbind(y_infy, y_tcs, y_wipro, y_hcl)
combined <- combined %>% mutate(Year = year(Date), Price = Close) %>% select(Stock, Price, Year) %>% filter(Year > 2003) %>% arrange(Stock, Year)

plot_ly(combined, x = ~Year, y = ~Price) %>% add_lines(color = ~Stock)
```

